<?php

/**
 * This is the model base class for the table "{{studentinvoice}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentInvoice".
 *
 * Columns in table "{{studentinvoice}}" available as properties of the model,
 * followed by relations of table "{{studentinvoice}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $reg_number
 * @property integer $semester_id
 * @property string $invoice_array
 * @property string $date_modified
 *
 * @property Student $regNumber
 * @property Semester $semester
 */
abstract class BaseStudentInvoice extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{studentinvoice}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Student Invoice|Student Invoices', $n);
	}

	public static function representingColumn() {
		return 'invoice_array';
	}

	public function rules() {
		return array(
			array('reg_number, semester_id', 'required'),
			array('semester_id', 'numerical', 'integerOnly'=>true),
			array('reg_number, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, reg_number, semester_id, invoice_array, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'regNumber' => array(self::BELONGS_TO, 'Student', 'reg_number'),
			'semester' => array(self::BELONGS_TO, 'Semester', 'semester_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'reg_number' => 'Students associated with the invoice',
			'semester_id' => 'Academic year | Semester',
			'invoice_array' => Yii::t('app', 'Fees associated with invoice'),
			'date_modified' => Yii::t('app', 'Date of entry'),
			'regNumber' => 'Students associated with the invoice',
			'semester' => null,
			'module_id'=>'Module type',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('reg_number', $this->reg_number);
		$criteria->compare('semester_id', $this->semester_id);
		$criteria->compare('invoice_array', $this->invoice_array, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}