<?php

/**
 * This is the model base class for the table "{{feepayable}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeePayable".
 *
 * Columns in table "{{feepayable}}" available as properties of the model,
 * followed by relations of table "{{feepayable}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $notes
 * @property integer $paid
 *
 * @property Feecategory $pa
 */
abstract class BaseFeePayable extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{feepayable}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Fees Payable|Fees Payables', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('paid', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>20),
			array('notes', 'length', 'max'=>200),
			array('name, notes, paid', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, notes, paid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pa' => array(self::BELONGS_TO, 'FeeCategory', 'paid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'notes' => Yii::t('app', 'Notes'),
			'paid' => null,
			'pa' => null,
			'programme'=>'Programme/ Course',
			
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('paid', $this->paid);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array('pageSize'=>50)
		));
	}
}