<?php

/**
 * This is the model base class for the table "{{studentreceipt}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentReceipt".
 *
 * Columns in table "{{studentreceipt}}" available as properties of the model,
 * followed by relations of table "{{studentreceipt}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $student_reg
 * @property string $receiptnumber
 * @property integer $bank_account_id
 * @property string $bankslip
 * @property string $amount
 * @property string $date_modified
 * @property integer $status
 *
 * @property Student $studentReg
 * @property Bankaccount $bankAccount
 */
abstract class BaseStudentReceipt extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{studentreceipt}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Student Receipt|Student Receipts', $n);
	}

	public static function representingColumn() {
		return 'receiptnumber';
	}

	public function rules() {
		return array(
			array('student_reg,  bank_account_id, bankslip, amount', 'required'),
			array('bank_account_id, status', 'numerical', 'integerOnly'=>true),
			array('student_reg, bankslip, amount, date_modified', 'length', 'max'=>30),
			array('receiptnumber', 'length', 'max'=>100),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, student_reg, receiptnumber, bank_account_id, bankslip, amount, date_modified, amount_in_words,user_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'studentReg' => array(self::BELONGS_TO, 'Student', 'student_reg'),
			'bankAccount' => array(self::BELONGS_TO, 'BankAccount', 'bank_account_id'),
			'cashier' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cashier'=>'Cashier Name',
			'student_reg' => null,
			'receiptnumber' => Yii::t('app', 'Receipt Number'),
			'bank_account_id' => 'Bank ',
			'bankslip' => Yii::t('app', 'Bankslip Ref. #'),
			'amount' => Yii::t('app', 'Amount received'),
			'date_modified' => Yii::t('app', 'Transaction Date'),
			'status' => Yii::t('app', 'Status'),
			'studentReg' => null,
			'bankAccount' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('student_reg', $this->student_reg);
		$criteria->compare('receiptnumber', $this->receiptnumber, true);
		$criteria->compare('bank_account_id', $this->bank_account_id);
		$criteria->compare('bankslip', $this->bankslip, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}