<?php

/**
 * This is the model base class for the table "{{institution}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Institution".
 *
 * Columns in table "{{institution}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $postal_address
 * @property string $physical_address
 * @property string $telephone
 * @property string $email
 * @property string $fax
 * @property string $photo
 * @property string $date_modified
 *
 */
abstract class BaseInstitution extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{institution}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Institution|Institutions', $n);
	}

	public static function representingColumn() {
		return 'date_modified';
	}

	public function rules() {
		return array(
			array('name, postal_address, physical_address, email, fax, photo', 'length', 'max'=>255),
			array('description', 'length', 'max'=>500),
			array('telephone, date_modified', 'length', 'max'=>30),
			array('name, description, postal_address, physical_address, telephone, email, fax, photo, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, postal_address, physical_address, telephone, email, fax, photo, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'postal_address' => Yii::t('app', 'Postal Address'),
			'physical_address' => Yii::t('app', 'Physical Address'),
			'telephone' => Yii::t('app', 'Telephone'),
			'email' => Yii::t('app', 'Email'),
			'fax' => Yii::t('app', 'Fax'),
			'photo' => Yii::t('app', 'Photo'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'changephoto'=>'Change institution photo',
			'changephotolabel'=>'Choose a new institution photo',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('postal_address', $this->postal_address, true);
		$criteria->compare('physical_address', $this->physical_address, true);
		$criteria->compare('telephone', $this->telephone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('photo', $this->photo, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}