<?php

/**
 * This is the model base class for the table "{{site_config}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SiteConfig".
 *
 * Columns in table "{{site_config}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $category
 * @property string $name
 * @property string $last_heart_beat
 * @property integer $error
 *
 */
abstract class BaseSiteConfig extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{site_config}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SiteConfig|SiteConfigs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('category, name, last_heart_beat, error', 'required'),
			array('category, error', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('last_heart_beat', 'length', 'max'=>30),
			array('id, category, name, last_heart_beat, error', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category' => Yii::t('app', 'Category'),
			'name' => Yii::t('app', 'Name'),
			'last_heart_beat' => Yii::t('app', 'Last Heart Beat'),
			'error' => Yii::t('app', 'Error'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category', $this->category);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('last_heart_beat', $this->last_heart_beat, true);
		$criteria->compare('error', $this->error);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}