<?php

/**
 * This is the model base class for the table "{{maritalstatus}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MaritalStatus".
 *
 * Columns in table "{{maritalstatus}}" available as properties of the model,
 * followed by relations of table "{{maritalstatus}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Applicant[] $applicants
 */
abstract class BaseMaritalStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{maritalstatus}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MaritalStatus|MaritalStatuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>10),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'applicants' => array(self::HAS_MANY, 'Applicant', 'marital_status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'applicants' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}