<?php

/**
 * This is the model base class for the table "{{semester}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Semester".
 *
 * Columns in table "{{semester}}" available as properties of the model,
 * followed by relations of table "{{semester}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $academicyear_id
 * @property string $starting
 * @property string $ending
 * @property string $date_modified
 *
 * @property Academicyear $academicyear
 */
abstract class BaseSemester extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{semester}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Semester|Semesters', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('academicyear_id', 'numerical', 'integerOnly'=>true),
			array('name, starting, ending', 'length', 'max'=>20),
			array('date_modified', 'length', 'max'=>30),
			array('name, academicyear_id, starting, ending, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, academicyear_id, starting, ending, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'academicyear' => array(self::BELONGS_TO, 'AcademicYear', 'academicyear_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'academicyear_id' => null,
			'starting' => Yii::t('app', 'Starting'),
			'ending' => Yii::t('app', 'Ending'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'academicyear' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('academicyear_id', $this->academicyear_id);
		$criteria->compare('starting', $this->starting, true);
		$criteria->compare('ending', $this->ending, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	
}