<?php

/**
 * This is the model base class for the table "{{academicyear}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcademicYear".
 *
 * Columns in table "{{academicyear}}" available as properties of the model,
 * followed by relations of table "{{academicyear}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $starting
 * @property string $ending
 * @property string $date_modified
 *
 * @property Applicationfees[] $applicationfees
 * @property Semester[] $semesters
 */
abstract class BaseAcademicYear extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{academicyear}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AcademicYear|AcademicYears', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, starting, ending', 'length', 'max'=>20),
			array('date_modified', 'length', 'max'=>30),
			array('name, starting, ending, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, starting, ending, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'applicationfees' => array(self::HAS_MANY, 'Applicationfees', 'academicyear_id'),
			'semesters' => array(self::HAS_MANY, 'Semester', 'academicyear_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'starting' => Yii::t('app', 'Starting'),
			'ending' => Yii::t('app', 'Ending'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'applicationfees' => "List of Applicants",
			'semesters' => "Semesters in this Academic Year",
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('starting', $this->starting, true);
		$criteria->compare('ending', $this->ending, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}