<?php

/**
 * This is the model base class for the table "{{department}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Department".
 *
 * Columns in table "{{department}}" available as properties of the model,
 * followed by relations of table "{{department}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $school_id
 * @property string $notes
 * @property string $date_modified
 * @property integer $status_id
 *
 * @property School $school
 * @property Programme[] $programmes
 */
abstract class BaseDepartment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{department}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Department|Departments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, school_id, date_modified', 'required'),
			array('school_id, status_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('code', 'length', 'max'=>10),
			array('notes', 'length', 'max'=>500),
			array('date_modified', 'length', 'max'=>30),
			array('code, notes, status_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, code, school_id, notes, date_modified, status_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'school' => array(self::BELONGS_TO, 'School', 'school_id'),
			'programmes' => array(self::HAS_MANY, 'Programme', 'department_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'code' => Yii::t('app', 'Code'),
			'school_id' => null,
			'notes' => Yii::t('app', 'Notes'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'status_id' => Yii::t('app', 'Status'),
			'school' => null,
			'programmes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('school_id', $this->school_id);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status_id', $this->status_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}