<?php

/**
 * This is the model base class for the table "{{programmetype}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProgrammeType".
 *
 * Columns in table "{{programmetype}}" available as properties of the model,
 * followed by relations of table "{{programmetype}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $notes
 *
 * @property Programme[] $programmes
 */
abstract class BaseProgrammeType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{programmetype}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProgrammeType|ProgrammeTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('code', 'length', 'max'=>10),
			array('name', 'length', 'max'=>20),
			array('notes', 'length', 'max'=>200),
			array('code, name, notes', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, name, notes', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'programmes' => array(self::HAS_MANY, 'Programme', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'notes' => Yii::t('app', 'Notes'),
			'programmes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('notes', $this->notes, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}