<?php

/**
 * This is the model base class for the table "{{programme}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Programme".
 *
 * Columns in table "{{programme}}" available as properties of the model,
 * followed by relations of table "{{programme}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $department_id
 * @property string $code
 * @property integer $type_id
 * @property integer $duration_id
 * @property string $notes
 * @property string $requirements
 * @property string $date_modified
 * @property integer $status_id
 *
 * @property Department $department
 * @property Programmetype $type
 * @property Programmeduration $duration
 */
abstract class BaseProgramme extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{programme}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Programme|Programmes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, code, department_id, type_id', 'required'),
			array('department_id, type_id, duration_id, status_id', 'numerical', 'integerOnly'=>true),
			array('name, requirements', 'length', 'max'=>255),
			array('code', 'length', 'max'=>10),
			array('notes', 'length', 'max'=>500),
			array('date_modified', 'length', 'max'=>30),
			array('code, duration_id, notes, requirements, date_modified, status_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, department_id, code, type_id, duration_id, notes, requirements, date_modified, status_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'department' => array(self::BELONGS_TO, 'Department', 'department_id'),
			'type' => array(self::BELONGS_TO, 'ProgrammeType', 'type_id'),
			'duration' => array(self::BELONGS_TO, 'ProgrammeDuration', 'duration_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'department_id' => null,
			'code' => Yii::t('app', 'Code'),
			'type_id' => null,
			'duration_id' => null,
			'notes' => Yii::t('app', 'Notes'),
			'requirements' => Yii::t('app', 'Requirements'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'status_id' => Yii::t('app', 'Status'),
			'department' => null,
			'type' => null,
			'duration' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('department_id', $this->department_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('duration_id', $this->duration_id);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('requirements', $this->requirements, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status_id', $this->status_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array('pageSize'=>1000)
		));
	}
}