<?php

/**
 * This is the model base class for the table "{{student_aspirant_agent}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StudentAspirantAgent".
 *
 * Columns in table "{{student_aspirant_agent}}" available as properties of the model,
 * followed by relations of table "{{student_aspirant_agent}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $aspirant_id
 * @property string $reg_number
 * @property string $id_number
 * @property integer $gender_id
 * @property string $surname
 * @property string $firstname
 * @property string $othername
 * @property integer $school_id
 * @property integer $department_id
 * @property string $programme_id
 * @property string $programme_end
 * @property string $mobile
 * @property string $email
 * @property string $date_modified
 *
 * @property School $school
 * @property Gender $gender
 * @property Department $department
 * @property Programme $programme
 */
abstract class BaseStudentAspirantAgent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{student_aspirant_agent}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StudentAspirantAgent|StudentAspirantAgents', $n);
	}

	public static function representingColumn() {
		return 'reg_number';
	}

	public function rules() {
		return array(
			array('aspirant_id, reg_number, id_number, gender_id, surname, firstname, school_id, department_id, programme_id, programme_end, mobile, email', 'required'),
			array('aspirant_id, gender_id, school_id, department_id', 'numerical', 'integerOnly'=>true),
			array('reg_number, surname, firstname, othername, programme_id, programme_end, date_modified', 'length', 'max'=>30),
			array('id_number', 'length', 'max'=>20),
			array('mobile', 'length', 'max'=>40),
			array('email', 'length', 'max'=>50),
			array('othername, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, aspirant_id, reg_number, id_number, gender_id, surname, firstname, othername, school_id, department_id, programme_id, programme_end, mobile, email, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'school' => array(self::BELONGS_TO, 'School', 'school_id'),
			'gender' => array(self::BELONGS_TO, 'Gender', 'gender_id'),
			'department' => array(self::BELONGS_TO, 'Department', 'department_id'),
			'programme' => array(self::BELONGS_TO, 'Programme', 'programme_id'),
			'aspirant' => array(self::BELONGS_TO, 'StudentAspirant', 'aspirant_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'aspirant_id' => Yii::t('app', 'Aspirant'),
			'reg_number' => Yii::t('app', 'Agent Reg Number'),
			'id_number' => Yii::t('app', 'Agent Id Number'),
			'gender_id' => null,
			'surname' => Yii::t('app', 'Agent Surname'),
			'firstname' => Yii::t('app', 'Agent Firstname'),
			'othername' => Yii::t('app', 'Agent Othername'),
			'school_id' => null,
			'department_id' => null,
			'programme_id' => null,
			'programme_end' => Yii::t('app', 'Agent Programme End'),
			'mobile' => Yii::t('app', 'Agent Mobile'),
			'email' => Yii::t('app', 'Agent Email'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'school' => null,
			'gender' => null,
			'department' => null,
			'programme' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('aspirant_id', $this->aspirant_id);
		$criteria->compare('reg_number', $this->reg_number, true);
		$criteria->compare('id_number', $this->id_number, true);
		$criteria->compare('gender_id', $this->gender_id);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('othername', $this->othername, true);
		$criteria->compare('school_id', $this->school_id);
		$criteria->compare('department_id', $this->department_id);
		$criteria->compare('programme_id', $this->programme_id);
		$criteria->compare('programme_end', $this->programme_end, true);
		$criteria->compare('mobile', $this->mobile, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}