<?php

/**
 * This is the model base class for the table "{{bursary}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bursary".
 *
 * Columns in table "{{bursary}}" available as properties of the model,
 * followed by relations of table "{{bursary}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $reg_number
 * @property string $date_created
 * @property string $date_modified
 * @property string $fee_balance
 * @property integer $guardian_status
 * @property string $f_name
 * @property string $f_id
 * @property string $f_occupation
 * @property string $m_name
 * @property string $m_id
 * @property string $m_occupation
 * @property string $g_name
 * @property string $g_id
 * @property string $g_occupation
 * @property string $fee_payment_plan
 * @property string $fee_payment
 * @property integer $bursary_beneficiary
 * @property string $beneficiary_amount
 *
 * @property Student $regNumber
 */
abstract class BaseBursary extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{bursary}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bursary|Bursaries', $n);
	}

	public static function representingColumn() {
		return 'date_created';
	}

	public function rules() {
		return array(
			array('reg_number, date_created, date_modified, guardian_status, bursary_beneficiary', 'required'),
			array('guardian_status, bursary_beneficiary', 'numerical', 'integerOnly'=>true),
			array('reg_number, date_created, date_modified, fee_balance, f_id, m_id, g_id, beneficiary_amount', 'length', 'max'=>30),
			array('f_name, f_occupation, m_name, m_occupation, g_name, g_occupation', 'length', 'max'=>100),
			array('fee_payment_plan, fee_payment', 'length', 'max'=>200),
			array('fee_balance, f_name, f_id, f_occupation, m_name, m_id, m_occupation, g_name, g_id, g_occupation, fee_payment_plan, fee_payment, beneficiary_amount', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, reg_number, date_created, date_modified, fee_balance, guardian_status, f_name, f_id, f_occupation, m_name, m_id, m_occupation, g_name, g_id, g_occupation, fee_payment_plan, fee_payment, bursary_beneficiary, beneficiary_amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'regNumber' => array(self::BELONGS_TO, 'Student', 'reg_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'reg_number' => null,
			'date_created' => Yii::t('app', 'Date Created'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'fee_balance' => Yii::t('app', 'Fee Balance'),
			'guardian_status' => Yii::t('app', 'Guardian Status'),
			'f_name' => Yii::t('app', 'Father Name'),
			'f_id' => Yii::t('app', 'Father ID Number'),
			'f_occupation' => Yii::t('app', 'Father Occupation'),
			'm_name' => Yii::t('app', 'Mother Name'),
			'm_id' => Yii::t('app', 'Mother ID Number'),
			'm_occupation' => Yii::t('app', 'Mother Occupation'),
			'g_name' => Yii::t('app', 'Guardian Name'),
			'g_id' => Yii::t('app', 'Guardian ID Number'),
			'g_occupation' => Yii::t('app', 'Guardian Occupation'),
			'fee_payment_plan' => Yii::t('app', 'Fee Payment Plan'),
			'fee_payment' => Yii::t('app', 'Fee Payment'),
			'bursary_beneficiary' => Yii::t('app', 'Bursary Beneficiary'),
			'beneficiary_amount' => Yii::t('app', 'Beneficiary Amount'),
			'regNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('reg_number', $this->reg_number);
		$criteria->compare('date_created', $this->date_created, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('fee_balance', $this->fee_balance, true);
		$criteria->compare('guardian_status', $this->guardian_status);
		$criteria->compare('f_name', $this->f_name, true);
		$criteria->compare('f_id', $this->f_id, true);
		$criteria->compare('f_occupation', $this->f_occupation, true);
		$criteria->compare('m_name', $this->m_name, true);
		$criteria->compare('m_id', $this->m_id, true);
		$criteria->compare('m_occupation', $this->m_occupation, true);
		$criteria->compare('g_name', $this->g_name, true);
		$criteria->compare('g_id', $this->g_id, true);
		$criteria->compare('g_occupation', $this->g_occupation, true);
		$criteria->compare('fee_payment_plan', $this->fee_payment_plan, true);
		$criteria->compare('fee_payment', $this->fee_payment, true);
		$criteria->compare('bursary_beneficiary', $this->bursary_beneficiary);
		$criteria->compare('beneficiary_amount', $this->beneficiary_amount, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}