<?php

/**
 * This is the model base class for the table "{{research_grant_claim}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResearchGrantClaim".
 *
 * Columns in table "{{research_grant_claim}}" available as properties of the model,
 * followed by relations of table "{{research_grant_claim}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $grant_id
 * @property integer $type_id
 * @property integer $staff_id
 * @property integer $school_id
 * @property integer $faculty_id
 * @property string $date_requested
 * @property string $amount_requested
 * @property string $amount_approved
 * @property string $report
 * @property string $aie
 * @property string $imprest_warrant
 * @property string $imprest_surrender
 * @property integer $school_approval_user
 * @property integer $school_approval_status
 * @property string $school_approval_remarks
 * @property integer $faculty_approval_user
 * @property integer $faculty_approval_status
 * @property string $faculty_approval_remarks
 * @property integer $research_approval_user
 * @property integer $research_approval_status
 * @property string $research_approval_remarks
 * @property integer $vc_approval_user
 * @property integer $vc_approval_status
 * @property string $vc_approval_remarks
 * @property integer $finance_approval_user
 * @property integer $finance_approval_status
 * @property string $finance_approval_remarks
 *
 * @property ResearchGrant $grant
 * @property Employee $staff
 */
abstract class BaseResearchGrantClaim extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{research_grant_claim}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResearchGrantClaim|ResearchGrantClaims', $n);
	}

	public static function representingColumn() {
		return 'date_requested';
	}

	public function rules() {
		return array(
			array('grant_id, type_id, staff_id, school_id, faculty_id, date_requested, amount_requested, amount_approved, school_approval_user, school_approval_status, faculty_approval_user, faculty_approval_status, research_approval_user, research_approval_status, vc_approval_user, vc_approval_status, finance_approval_user, finance_approval_status', 'required'),
			array('grant_id, type_id, staff_id, school_id, faculty_id, school_approval_user, school_approval_status, faculty_approval_user, faculty_approval_status, research_approval_user, research_approval_status, vc_approval_user, vc_approval_status, finance_approval_user, finance_approval_status', 'numerical', 'integerOnly'=>true),
			array('date_requested,school_approval_date,faculty_approval_date,research_approval_date,vc_approval_date,finance_approval_date, surrender_date', 'length', 'max'=>20),
			array('amount_requested', 'numerical'),
			array('report, aie, imprest_warrant, imprest_surrender', 'length', 'max'=>100),
			array('report, aie, imprest_warrant, imprest_surrender',  'file', 'types'=>'pdf','wrongType'=>'Please save the surrender document as PDF', 'on'=>'surrender'),
			array('school_approval_remarks, faculty_approval_remarks, research_approval_remarks, vc_approval_remarks, finance_approval_remarks', 'length', 'max'=>500),
			array('report, aie, imprest_warrant, imprest_surrender, school_approval_remarks, faculty_approval_remarks, research_approval_remarks, vc_approval_remarks, finance_approval_remarks', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, grant_id, type_id, staff_id, school_id, faculty_id, date_requested, amount_requested, amount_approved, report, aie, imprest_warrant, imprest_surrender, school_approval_user, school_approval_status, school_approval_remarks, faculty_approval_user, faculty_approval_status, faculty_approval_remarks, research_approval_user, research_approval_status, research_approval_remarks, vc_approval_user, vc_approval_status, vc_approval_remarks, finance_approval_user, finance_approval_status, finance_approval_remarks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'grant' => array(self::BELONGS_TO, 'ResearchGrant', 'grant_id'),
			'staff' => array(self::BELONGS_TO, 'Employee', 'staff_id'),
			'school' => array(self::BELONGS_TO, 'School', 'school_id'),
			'faculty' => array(self::BELONGS_TO, 'Faculty', 'faculty_id'),
			'schoolUser' => array(self::BELONGS_TO, 'User', 'school_approval_user'),
			'facultyUser' => array(self::BELONGS_TO, 'User', 'faculty_approval_user'),
			'researchUser' => array(self::BELONGS_TO, 'User', 'research_approval_user'),
			'vcUser' => array(self::BELONGS_TO, 'User', 'vc_approval_user'),
			'financeUser' => array(self::BELONGS_TO, 'User', 'finance_approval_user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'grant_id' => null,
			'type_id' => Yii::t('app', 'Type'),
			'staff_id' => null,
			'school_id' => Yii::t('app', 'School'),
			'faculty_id' => Yii::t('app', 'Faculty'),
			'date_requested' => Yii::t('app', 'Date Requested'),
			'amount_requested' => Yii::t('app', 'Amount Requested'),
			'amount_approved' => Yii::t('app', 'Amount Approved'),
			'report' => Yii::t('app', 'Progress Report'),
			'aie' => Yii::t('app', 'Copy of Authority to Incur Expenditure'),
			'imprest_warrant' => Yii::t('app', 'Copy of Imprest Warrant Form'),
			'imprest_surrender' => Yii::t('app', 'Copy of Imprest Surrender Form'),
			'school_approval_user' => Yii::t('app', 'School Approval User'),
			'school_approval_status' => Yii::t('app', 'School Approval Status'),
			'school_approval_remarks' => Yii::t('app', 'School Approval Remarks'),
			'faculty_approval_user' => Yii::t('app', 'Faculty Approval User'),
			'faculty_approval_status' => Yii::t('app', 'Faculty Approval Status'),
			'faculty_approval_remarks' => Yii::t('app', 'Faculty Approval Remarks'),
			'research_approval_user' => Yii::t('app', 'Research Approval User'),
			'research_approval_status' => Yii::t('app', 'Research Approval Status'),
			'research_approval_remarks' => Yii::t('app', 'Research Approval Remarks'),
			'vc_approval_user' => Yii::t('app', 'Vc Approval User'),
			'vc_approval_status' => Yii::t('app', 'Vc Approval Status'),
			'vc_approval_remarks' => Yii::t('app', 'Vc Approval Remarks'),
			'finance_approval_user' => Yii::t('app', 'Finance Approval User'),
			'finance_approval_status' => Yii::t('app', 'Finance Approval Status'),
			'finance_approval_remarks' => Yii::t('app', 'Finance Approval Remarks'),
			'grant' => null,
			'staff' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('grant_id', $this->grant_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('school_id', $this->school_id);
		$criteria->compare('faculty_id', $this->faculty_id);
		$criteria->compare('date_requested', $this->date_requested, true);
		$criteria->compare('amount_requested', $this->amount_requested, true);
		$criteria->compare('amount_approved', $this->amount_approved, true);
		$criteria->compare('report', $this->report, true);
		$criteria->compare('aie', $this->aie, true);
		$criteria->compare('imprest_warrant', $this->imprest_warrant, true);
		$criteria->compare('imprest_surrender', $this->imprest_surrender, true);
		$criteria->compare('school_approval_user', $this->school_approval_user);
		$criteria->compare('school_approval_status', $this->school_approval_status);
		$criteria->compare('school_approval_remarks', $this->school_approval_remarks, true);
		$criteria->compare('faculty_approval_user', $this->faculty_approval_user);
		$criteria->compare('faculty_approval_status', $this->faculty_approval_status);
		$criteria->compare('faculty_approval_remarks', $this->faculty_approval_remarks, true);
		$criteria->compare('research_approval_user', $this->research_approval_user);
		$criteria->compare('research_approval_status', $this->research_approval_status);
		$criteria->compare('research_approval_remarks', $this->research_approval_remarks, true);
		$criteria->compare('vc_approval_user', $this->vc_approval_user);
		$criteria->compare('vc_approval_status', $this->vc_approval_status);
		$criteria->compare('vc_approval_remarks', $this->vc_approval_remarks, true);
		$criteria->compare('finance_approval_user', $this->finance_approval_user);
		$criteria->compare('finance_approval_status', $this->finance_approval_status);
		$criteria->compare('finance_approval_remarks', $this->finance_approval_remarks, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}