<?php

/**
 * This is the model base class for the table "{{admission}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Admission".
 *
 * Columns in table "{{admission}}" available as properties of the model,
 * followed by relations of table "{{admission}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $semester_id
 * @property string $reg_number
 * @property integer $year_of_study
 * @property integer $semester_of_study
 * @property string $date_modified
 *
 * @property Semester $semester
 * @property Student $regNumber
 */
abstract class BaseAdmission extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{admission}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Admission|Admissions', $n);
	}

	public static function representingColumn() {
		return 'regNumber';
	}

	public function rules() {
		return array(
			array('semester_id, reg_number, year_of_study, semester_of_study, date_modified', 'required'),
			array('semester_id, year_of_study, semester_of_study', 'numerical', 'integerOnly'=>true),
			array('reg_number, date_modified', 'length', 'max'=>30),
			array('id, semester_id, reg_number, year_of_study, semester_of_study, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'semester' => array(self::BELONGS_TO, 'Semester', 'semester_id'),
			'regNumber' => array(self::BELONGS_TO, 'Student', 'reg_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'semester_id' => 'University Semester',
			'reg_number' => 'Student Reg. Number',
			'year_of_study' => Yii::t('app', 'Year Of Study'),
			'semester_of_study' => Yii::t('app', 'Semester/Term Of Study'),
			'date_modified' => Yii::t('app', 'Date of Admission'),
			'semester' => 'University Semester',
			'regNumber' => 'Student Reg. Number',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('semester_id', $this->semester_id);
		$criteria->compare('reg_number', $this->reg_number);
		$criteria->compare('year_of_study', $this->year_of_study);
		$criteria->compare('semester_of_study', $this->semester_of_study);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}