<?php

/**
 * This is the model base class for the table "{{bursary_award}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BursaryAward".
 *
 * Columns in table "{{bursary_award}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $reg_number
 * @property string $amount
 * @property string $period
 * @property string $date_modified
 *
 */
abstract class BaseBursaryAward extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{bursary_award}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BursaryAward|BursaryAwards', $n);
	}

	public static function representingColumn() {
		return 'reg_number';
	}

	public function rules() {
		return array(
			array('reg_number, amount, period', 'required'),
			array('reg_number, amount, period, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, reg_number, amount, period, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'reg_number' => Yii::t('app', 'Reg Number'),
			'amount' => Yii::t('app', 'Amount'),
			'period' => Yii::t('app', 'Period'),
			'date_modified' => Yii::t('app', 'Date Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('reg_number', $this->reg_number, true);
		$criteria->compare('amount', $this->amount, true);
		$criteria->compare('period', $this->period, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}