<?php

/**
 * This is the model base class for the table "{{project_phase}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProjectPhase".
 *
 * Columns in table "{{project_phase}}" available as properties of the model,
 * followed by relations of table "{{project_phase}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $content
 * @property string $date_added
 * @property string $date_modified
 * @property integer $status_id
 *
 * @property ProjectActivity[] $projectActivities
 * @property Status $status
 */
abstract class BaseProjectPhase extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{project_phase}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Project Phase|Project Phases', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, content', 'required'),
			array('status_id', 'numerical', 'integerOnly'=>true),
			array('name, date_added, date_modified', 'length', 'max'=>30),
			array('date_added, date_modified, status_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, content, date_added, date_modified, status_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'projectActivities' => array(self::HAS_MANY, 'ProjectActivity', 'phase_id'),
			'status' => array(self::BELONGS_TO, 'Status', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'content' => Yii::t('app', 'Description'),
			'date_added' => Yii::t('app', 'Date Added'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'status_id' => null,
			'projectActivities' => null,
			'status' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('LOWER(name)', strtolower($this->name), true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('date_added', $this->date_added, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status_id', $this->status_id);
		$criteria->order='id DESC';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array('pageSize'=>50)
		));
	}
}