<?php

/**
 * This is the model base class for the table "{{comment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comment".
 *
 * Columns in table "{{comment}}" available as properties of the model,
 * followed by relations of table "{{comment}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $content
 * @property integer $author_id
 * @property integer $category_id
 * @property string $date_added
 * @property string $date_modified
 * @property integer $status_id
 *
 * @property User $author
 * @property Status $status
 */
abstract class BaseComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{comment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comment|Comments', $n);
	}

	public static function representingColumn() {
		return 'content';
	}

	public function rules() {
		return array(
			array('content, author_id, category_id', 'required'),
			array('author_id, category_id, status_id', 'numerical', 'integerOnly'=>true),
			array('date_added, date_modified', 'length', 'max'=>30),
			array('date_added, date_modified, status_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, content, author_id, category_id, date_added, date_modified, status_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'author' => array(self::BELONGS_TO, 'User', 'author_id'),
			'status' => array(self::BELONGS_TO, 'Status', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'content' => Yii::t('app', 'Content'),
			'author_id' => null,
			'category_id' => Yii::t('app', 'Category'),
			'date_added' => Yii::t('app', 'Date Added'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'status_id' => null,
			'author' => null,
			'status' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('date_added', $this->date_added, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status_id', $this->status_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}