<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);
?><?php
$this->menu = array(
	array('label' => Yii::t('app', 'List all') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create New') . ' ' . $model->label(), 'url'=>array('create')),
);
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'previous-student-grid',
	'type'=>'striped bordered condensed',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		array(
			'name'=>'course_code',
			'value'=>'GxHtml::valueEx($data->class)',
			'filter'=>GxHtml::listDataEx(CourseClass::model()->findAllAttributes(null, true)),
		),
		'course_code',
		'reg_number',
		'sex',
		'course_year',
		'study_year',
		'surname',
		'name1',
		'name2',
		'scat',
		/*'dob',
		'address1',
		'address2',
		'box',
		'town',
		'phone',
		'extension',
		'district',
		'id_number',
		'kencit',
		'fee_payer',
		'employed',
		'employer',
		'employment_department',
		'employer_box',
		'employer_town',
		'employer_phone',
		'location',
		'sub_location',
		'tlc',
		'pat_date',
		'pat',
		'fee_date',
		'term_address',
		'term_box',
		'term_town',
		'nok_name',
		'nok_box',
		'nok_town',
		'nok_phone',
		'fee_arrears',
		'eoy_res',
		'xr',
		'xrsig',
		'cc',
		'ccsig',
		'lc',
		'lcsig',
		'prn',
		'registered',
		'cref',
		'theid',
		'abal',
		'rs',
		'sponsor_no',
		'old_number',
		'username',
		'date',
		'scat',
		'statsig',
		'statdata',
		'libreg',
		'lregcomm',
		'lreguser',
		'lregdate',
		'lib_arrears',
		'libmess1',
		'override',
		'hostel',
		'host_term',
		'h_fee_date',
		'hostarrear',
		'prov',
		'dist',
		'hos_arrear',
		'lreg',
		'lof',
		'lcnumber',
		array(
				'name'=>'module_id',
				'value'=>'GxHtml::valueEx($data->module)',
				'filter'=>GxHtml::listDataEx(Module::model()->findAllAttributes(null, true)),
				),
		'date_modified',
		*/
		array(
			'class' => 'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>