<?php

/**
 * This is the model base class for the table "{{email}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Email".
 *
 * Columns in table "{{email}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $email
 * @property string $reg_number
 *
 */
abstract class BaseEmail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{email}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Email|Emails', $n);
	}

	public static function representingColumn() {
		return 'reg_number';
	}

	public function rules() {
		return array(
			array('reg_number', 'required'),
			array('email', 'length', 'max'=>50),
			array('reg_number', 'length', 'max'=>30),
			array('email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, email, reg_number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'reg_number' => Yii::t('app', 'Reg Number'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('reg_number', $this->reg_number, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}