<?php

/**
 * This is the model base class for the table "{{permanent_period}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PermanentPeriod".
 *
 * Columns in table "{{permanent_period}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $duration
 *
 */
abstract class BasePermanentPeriod extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{permanent_period}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Permanent Duration|Permanent Durations', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('duration', 'required'),
			array('duration', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, duration', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'duration' => Yii::t('app', 'Duration  in years'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('duration', $this->duration);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}