<?php

/**
 * This is the model base class for the table "{{employee_leave_day}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeLeaveDay".
 *
 * Columns in table "{{employee_leave_day}}" available as properties of the model,
 * followed by relations of table "{{employee_leave_day}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $leave_id
 * @property integer $staff_id
 * @property string $pf_number
 * @property integer $year
 * @property integer $total
 * @property integer $bf
 * @property integer $used
 * @property integer $balance
 * @property string $date_modified
 *
 * @property EmployeeLeave $leave
 * @property Employee $staff
 */
abstract class BaseEmployeeLeaveDay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_leave_day}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeLeaveDay|EmployeeLeaveDays', $n);
	}

	public static function representingColumn() {
		return 'pf_number';
	}

	public function rules() {
		return array(
			array('leave_id, staff_id, pf_number, year, total, bf, used, balance', 'required'),
			array('leave_id, staff_id, year, total, bf, used, balance', 'numerical', 'integerOnly'=>true),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, leave_id, staff_id, pf_number, year, total, bf, used, balance, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'leave' => array(self::BELONGS_TO, 'EmployeeLeave', 'leave_id'),
			'staff' => array(self::BELONGS_TO, 'Employee', 'staff_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'leave_id' => null,
			'staff_id' => null,
			'pf_number' => Yii::t('app', 'Pf Number'),
			'year' => Yii::t('app', 'Year'),
			'total' => Yii::t('app', 'Total'),
			'bf' => Yii::t('app', 'Bf'),
			'used' => Yii::t('app', 'Used'),
			'balance' => Yii::t('app', 'Balance'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'leave' => null,
			'staff' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('leave_id', $this->leave_id);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('pf_number', $this->pf_number, true);
		$criteria->compare('year', $this->year);
		$criteria->compare('total', $this->total);
		$criteria->compare('bf', $this->bf);
		$criteria->compare('used', $this->used);
		$criteria->compare('balance', $this->balance);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}