<?php

/**
 * This is the model base class for the table "{{library_klisc}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LibraryKlisc".
 *
 * Columns in table "{{library_klisc}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $research_priorities
 * @property string $contact_person
 * @property string $address
 * @property string $telephone
 * @property string $email
 * @property string $ip_addresses
 * @property string $user_population
 * @property string $date_modified
 *
 */
abstract class BaseLibraryKlisc extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{library_klisc}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'KLISC Consortium|KLISC Consortium', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, name, type, research_priorities, contact_person, address, telephone, email, ip_addresses, user_population', 'required'),
			array('name, address', 'length', 'max'=>400),
			array('type, contact_person, telephone', 'length', 'max'=>300),
			array('research_priorities', 'length', 'max'=>800),
			array('email, ip_addresses', 'length', 'max'=>500),
			array('date_modified', 'length', 'max'=>30),
			array('user_population', 'safe'),
			array('name, type, research_priorities, contact_person, address, telephone, email, ip_addresses, user_population, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, type, views, research_priorities, contact_person, address, telephone, email, ip_addresses, user_population, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
			'research_priorities' => Yii::t('app', 'Research Priorities'),
			'contact_person' => Yii::t('app', 'Contact Person'),
			'address' => Yii::t('app', 'Address'),
			'telephone' => Yii::t('app', 'Telephone'),
			'email' => Yii::t('app', 'Email'),
			'ip_addresses' => Yii::t('app', 'Ip Addresses'),
			'user_population' => Yii::t('app', 'User Population'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'views' => Yii::t('app', 'Number of Views'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('research_priorities', $this->research_priorities, true);
		$criteria->compare('contact_person', $this->contact_person, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('telephone', $this->telephone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('ip_addresses', $this->ip_addresses, true);
		$criteria->compare('user_population', $this->user_population, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}