<?php

/**
 * This is the model base class for the table "{{employee_leave}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeLeave".
 *
 * Columns in table "{{employee_leave}}" available as properties of the model,
 * followed by relations of table "{{employee_leave}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $duration_id
 * @property integer $notice_days
 * @property string $date_modified
 *
 * @property EmployeeLeaveDuration $duration
 * @property EmployeeLeaveApplication[] $employeeLeaveApplications
 */
abstract class BaseEmployeeLeave extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_leave}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Leave|Leave', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, duration_id, notice_days', 'required'),
			array('duration_id, notice_days', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('date_modified', 'length', 'max'=>50),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, duration_id, notice_days, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'duration' => array(self::BELONGS_TO, 'EmployeeLeaveDuration', 'duration_id'),
			'employeeLeaveApplications' => array(self::HAS_MANY, 'EmployeeLeaveApplication', 'leave_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'duration_id' => null,
			'notice_days' => Yii::t('app', 'Notice Days'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'duration' => null,
			'employeeLeaveApplications' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('duration_id', $this->duration_id);
		$criteria->compare('notice_days', $this->notice_days);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}