<?php

/**
 * This is the model base class for the table "{{position}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Position".
 *
 * Columns in table "{{position}}" available as properties of the model,
 * followed by relations of table "{{position}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $office_id
 *
 * @property Office $office
 */
abstract class BasePosition extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{position}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Position|Positions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, office_id', 'required'),
			array('office_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, office_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'office' => array(self::BELONGS_TO, 'Office', 'office_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'office_id' => null,
			'office' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('LOWER(name)', strtolower($this->name), true);
		$criteria->compare('office_id', $this->office_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}