<?php

/**
 * This is the model base class for the table "{{employee_qualification}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeQualification".
 *
 * Columns in table "{{employee_qualification}}" available as properties of the model,
 * followed by relations of table "{{employee_qualification}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $pf_number
 * @property integer $level_id
 * @property string $name
 * @property string $institution
 * @property string $year
 * @property string $award
 * @property string $date_modified
 *
 * @property Employee $pfNumber
 * @property Programmetype $level
 */
abstract class BaseEmployeeQualification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_qualification}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Qualification|Qualifications', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('pf_number, level_id, name, institution, country_id, year, award', 'required'),
			array('level_id', 'numerical', 'integerOnly'=>true),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('name, institution, award', 'length', 'max'=>600),
			array('year', 'length', 'max'=>10),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, pf_number, level_id, name, institution, year, award, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
			'level' => array(self::BELONGS_TO, 'EmployeeQualificationLevel', 'level_id'),
			'country' => array(self::BELONGS_TO, 'EmployeeCountry', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pf_number' => null,
			'level_id' => Yii::t('app', 'Level of Qualification'),
			'name' => Yii::t('app', 'Area of Qualification '),
			'institution' => Yii::t('app', 'Name of Institution'),
			'country_id' => Yii::t('app', 'Country'),
			'year' => Yii::t('app', 'Completion Year'),
			'award' => Yii::t('app', 'Award eg Pass, Distinction,'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'pfNumber' => null,
			'level' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('level_id', $this->level_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('institution', $this->institution, true);
		$criteria->compare('year', $this->year, true);
		$criteria->compare('award', $this->award, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->order='level_id ASC';
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}