<?php

/**
 * This is the model base class for the table "{{employee_bank}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeBank".
 *
 * Columns in table "{{employee_bank}}" available as properties of the model,
 * followed by relations of table "{{employee_bank}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $pf_number
 * @property integer $bank_id
 * @property string $account_number
 * @property string $branch
 * @property boolean $status
 * @property string $date_modified
 *
 * @property Bankaccount $bank
 * @property Employee $pfNumber
 */
abstract class BaseEmployeeBank extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_bank}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeBank|EmployeeBanks', $n);
	}

	public static function representingColumn() {
		return 'account_number';
	}

	public function rules() {
		return array(
			array('pf_number, bank_id, account_number, branch', 'required'),
			array('bank_id', 'numerical', 'integerOnly'=>true),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('account_number, branch', 'length', 'max'=>50),
			array('status', 'safe'),
			array('status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, pf_number, bank_id, account_number, branch, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bank' => array(self::BELONGS_TO, 'BankAccount', 'bank_id'),
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pf_number' => null,
			'bank_id' => null,
			'account_number' => Yii::t('app', 'Account Number'),
			'branch' => Yii::t('app', 'Branch'),
			'status' => Yii::t('app', 'Active'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'bank' => null,
			'pfNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('bank_id', $this->bank_id);
		$criteria->compare('account_number', $this->account_number, true);
		$criteria->compare('branch', $this->branch, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}