<?php

/**
 * This is the model base class for the table "{{salary_scale}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SalaryScale".
 *
 * Columns in table "{{salary_scale}}" available as properties of the model,
 * followed by relations of table "{{salary_scale}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $step
 * @property integer $grade_id
 * @property integer $category_id
 * @property string $basic_salary
 * @property string $house_allowance
 * @property integer $status
 * @property string $date_modified
 *
 * @property EmployeeEmployment[] $employeeEmployments
 * @property Grade $grade
 * @property EmployeeCategory $category
 */
abstract class BaseSalaryScale extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{salary_scale}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Salary Scale|Salary Scales', $n);
	}

	public static function representingColumn() {
		return 'step';
	}

	public function rules() {
		return array(
			array('step, grade_id, category_id, basic_salary, house_allowance', 'required'),
			array('grade_id, category_id, status', 'numerical', 'integerOnly'=>true),
			array('step', 'length', 'max'=>15),
			array('date_modified', 'length', 'max'=>30),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, step, grade_id, category_id, basic_salary, house_allowance, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeeEmployments' => array(self::HAS_MANY, 'EmployeeEmployment', 'salary_scale_id'),
			'grade' => array(self::BELONGS_TO, 'Grade', 'grade_id'),
			'category' => array(self::BELONGS_TO, 'EmployeeCategory', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'step' => Yii::t('app', 'Step'),
			'grade_id' => null,
			'category_id' => null,
			'basic_salary' => Yii::t('app', 'House Allowance'),
			'house_allowance' => Yii::t('app', 'Basic Salary'),
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'employeeEmployments' => null,
			'grade' => null,
			'category' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('step', $this->step, true);
		$criteria->compare('grade_id', $this->grade_id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('basic_salary', $this->basic_salary);
		$criteria->compare('house_allowance', $this->house_allowance);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array('pageSize'=>300),
		));
	}
}