<?php

/**
 * This is the model base class for the table "{{employee_qualification_level}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeQualificationLevel".
 *
 * Columns in table "{{employee_qualification_level}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $weight
 *
 */
abstract class BaseEmployeeQualificationLevel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_qualification_level}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeQualificationLevel|EmployeeQualificationLevels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('weight', 'required'),
			array('weight', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'weight' => Yii::t('app', 'Weight'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('weight', $this->weight);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}