<?php

/**
 * This is the model base class for the table "{{staff_menu_link}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StaffMenuLink".
 *
 * Columns in table "{{staff_menu_link}}" available as properties of the model,
 * followed by relations of table "{{staff_menu_link}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $label_name
 * @property string $url
 * @property string $description
 * @property integer $weight
 * @property string $date_modified
 * @property string $icon
 * @property integer $status
 *
 * @property StaffMenuAccess[] $staffMenuAccesses
 */
abstract class BaseStaffMenuLink extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{staff_menu_link}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StaffMenuLink|StaffMenuLinks', $n);
	}

	public static function representingColumn() {
		return 'label_name';
	}

	public function rules() {
		return array(
			array('parent_id, label_name, url, description, weight, status', 'required'),
			array('parent_id, weight, status', 'numerical', 'integerOnly'=>true),
			array('label_name', 'length', 'max'=>100),
			array('url', 'length', 'max'=>200),
			array('description', 'length', 'max'=>300),
			array('date_modified, icon', 'length', 'max'=>30),
			array('date_modified, icon', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent_id, label_name, url, description, weight, date_modified, icon, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staffMenuAccesses' => array(self::HAS_MANY, 'StaffMenuAccess', 'menu_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_id' => Yii::t('app', 'Parent'),
			'label_name' => Yii::t('app', 'Label Name'),
			'url' => Yii::t('app', 'Url'),
			'description' => Yii::t('app', 'Description'),
			'weight' => Yii::t('app', 'Weight'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'icon' => Yii::t('app', 'Icon'),
			'status' => Yii::t('app', 'Status'),
			'staffMenuAccesses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('id', $this->id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('label_name', $this->label_name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('weight', $this->weight);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('icon', $this->icon, true);
		$criteria->compare('status', $this->status);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}