<?php

/**
 * This is the model base class for the table "{{employee}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Employee".
 *
 * Columns in table "{{employee}}" available as properties of the model,
 * followed by relations of table "{{employee}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $title_id
 * @property string $surname
 * @property string $firstname
 * @property string $othername
 * @property integer $gender_id
 * @property string $id_number
 * @property string $pin_number
 * @property string $nssf_number
 * @property string $nhif_number
 * @property string $dob
 * @property string $pf_number
 * @property integer $emp_terms_id
 * @property string $doe
 * @property string $dot
 * @property integer $status
 * @property string $date_modified
 *
 * @property Gender $gender
 * @property EmpTerms $empTerms
 * @property Title $title
 * @property EmployeeContact[] $employeeContacts
 * @property EmployeeEmployment[] $employeeEmployments
 * @property EmployeeQualification[] $employeeQualifications
 */
abstract class BaseEmployee extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Employee|Employees', $n);
	}

	public static function representingColumn() {
		return array('title','firstname','othername', 'surname');
	}

	public function rules() {
		return array(
			array('title_id, surname, firstname, gender_id,ethnicity_id,religion_id, id_number, pin_number, nssf_number, nhif_number, dob, pf_number, emp_terms_id, doe, status', 'required'),
			array('title_id, gender_id, emp_terms_id, highest_qualification_id, current_designation_id, status', 'numerical', 'integerOnly'=>true),
			array('surname, firstname, othername, dob, doe, dot, date_modified, termination_reason', 'length', 'max'=>30),
			array('id_number, pin_number, nssf_number, nhif_number, pf_number', 'length', 'max'=>20),
			array('othername, dot, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title_id, surname, firstname, othername, gender_id, id_number, pin_number, nssf_number, nhif_number, dob, pf_number, emp_terms_id, doe, dot, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'gender' => array(self::BELONGS_TO, 'Gender', 'gender_id'),
			'ethnicity' => array(self::BELONGS_TO, 'Ethnicity', 'ethnicity_id'),
			'religion' => array(self::BELONGS_TO, 'Religion', 'religion_id'),
			'empTerms' => array(self::BELONGS_TO, 'EmploymentTerms', 'emp_terms_id'),
			'title' => array(self::BELONGS_TO, 'Title', 'title_id'),
			'employeeContacts' => array(self::HAS_MANY, 'EmployeeContact', 'pf_number'),
			'contact' => array(self::HAS_MANY, 'EmployeeContact', 'pf_number'),
			'employeeEmployments' => array(self::HAS_MANY, 'EmployeeEmployment', 'pf_number'),
			'employeeBanks' => array(self::HAS_MANY, 'EmployeeBank', 'pf_number'),
			'employeeQualifications' => array(self::HAS_MANY, 'EmployeeQualification', 'pf_number'),
			'employeeDependants' => array(self::HAS_MANY, 'EmployeeDependant', 'pf_number'),
			'employeeNextOfKin' => array(self::HAS_MANY, 'EmployeeNok', 'pf_number'),
			'employeeBeneficiary' => array(self::HAS_MANY, 'EmployeeBeneficiary', 'pf_number'),
			'employeeDisability' => array(self::HAS_MANY, 'EmployeeDisability', 'pf_number'),
			'employeeDocs' => array(self::HAS_MANY, 'EmployeeDoc', 'pf_number'),
			'employeeWorkExperience' => array(self::HAS_MANY, 'EmployeeWork', 'pf_number'),
			'employeeStatement' => array(self::HAS_MANY, 'EmployeeStatement', 'pf_number'),
			'employeeBanks' => array(self::HAS_MANY, 'EmployeeBank', 'pf_number'),
			'employeeQualifications' => array(self::HAS_MANY, 'EmployeeQualification', 'pf_number'),
			'employeeDependants' => array(self::HAS_MANY, 'EmployeeDependant', 'pf_number'),
			'employeeNextOfKin' => array(self::HAS_MANY, 'EmployeeNok', 'pf_number'),
			'employeeDisability' => array(self::HAS_MANY, 'EmployeeDisability', 'pf_number'),
			'employeeProject' => array(self::HAS_MANY, 'EmployeeProject', 'pf_number'),
			'employeePublication' => array(self::HAS_MANY, 'EmployeePublication', 'pf_number'),
			'employeeSupervision' => array(self::HAS_MANY, 'EmployeeSupervision', 'pf_number'),
			'employeeCourseTaught' => array(self::HAS_MANY, 'EmployeeCourseTaught', 'pf_number'),
			'employeeProfessional' => array(self::HAS_MANY, 'EmployeeProfessional', 'pf_number'),
			'employeeExtra' => array(self::HAS_MANY, 'EmployeeExtra', 'pf_number'),
			'currentEmployment' => array(self::BELONGS_TO, 'EmployeeEmployment', 'current_designation_id'),
			'hqualification' => array(self::BELONGS_TO, 'EmployeeQualificationLevel', 'highest_qualification_id'),
			'employment' => array(self::BELONGS_TO, 'EmployeeEmployment', 'current_employment_id'),
			'employeeCourses' => array(self::HAS_MANY, 'EmployeeCourse', 'pf_number'),
			'securityQuestion' => array(self::BELONGS_TO, 'UserQuestion', 'security_question_id'),
			
					
			
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title_id' => null,
			'surname' => Yii::t('app', 'Surname'),
			'firstname' => Yii::t('app', 'First name'),
			'othername' => Yii::t('app', 'Other name'),
			'gender_id' => null,
			'id_number' => Yii::t('app', 'ID/ Passport Number'),
			'pin_number' => Yii::t('app', 'PIN'),
			'nssf_number' => Yii::t('app', 'NSSF Number'),
			'nhif_number' => Yii::t('app', 'NHIF Number'),
			'dob' => Yii::t('app', 'Date of birth'),
			'pf_number' => Yii::t('app', 'PF Number'),
			'emp_terms_id' => Yii::t('app', 'Terms of First Employment'),
			'doe' => Yii::t('app', 'Date of First Employment'),
			'dot' => Yii::t('app', 'Date of termination'),
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'religion_id' => Yii::t('app', 'Religion'),
			'ethnicity_id' => Yii::t('app', 'Ethnicity'),
			'gender' => null,
			'empTerms' => null,
			'title' => null,
			'employeeContacts' => Yii::t('app', 'Contact Information'),
			'employeeEmployments' => Yii::t('app', 'Employment'),
			'employeeQualifications' => Yii::t('app', 'Qualifications'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title_id', $this->title_id);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('othername', $this->othername, true);
		$criteria->compare('gender_id', $this->gender_id);
		$criteria->compare('id_number', $this->id_number, true);
		$criteria->compare('pin_number', $this->pin_number, true);
		$criteria->compare('nssf_number', $this->nssf_number, true);
		$criteria->compare('nhif_number', $this->nhif_number, true);
		$criteria->compare('dob', $this->dob, true);
		$criteria->compare('pf_number', $this->pf_number, true);
		$criteria->compare('emp_terms_id', $this->emp_terms_id);
		$criteria->compare('doe', $this->doe, true);
		$criteria->compare('dot', $this->dot, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}