<?php

/**
 * This is the model base class for the table "{{employee_leave_application}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeLeaveApplication".
 *
 * Columns in table "{{employee_leave_application}}" available as properties of the model,
 * followed by relations of table "{{employee_leave_application}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $leave_id
 * @property integer $staff_id
 * @property string $start_date
 * @property string $end_date
 * @property integer $total_days
 * @property integer $taken_days
 * @property integer $rem_days
 * @property integer $status
 * @property boolean $is_latest
 * @property string $date_modified
 *
 * @property Employee $staff
 * @property EmployeeLeave $leave
 */
abstract class BaseEmployeeLeaveApplication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_leave_application}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Leave Application|Leave Applications', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('leave_id, staff_id, start_date, end_date, total_days, taken_days, rem_days, hod_id, status', 'required'),
			array('leave_id, staff_id, while_away_staff_id, total_days, taken_days, rem_days, status', 'numerical', 'integerOnly'=>true),
			array('start_date, end_date, date_modified', 'length', 'max'=>50),
			array('hod_approval_remarks', 'length', 'max'=>300),
			array('is_latest', 'safe'),
			array('is_latest, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, leave_id, staff_id, start_date, end_date, total_days, taken_days, rem_days, status, is_latest, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staff' => array(self::BELONGS_TO, 'Employee', 'staff_id'),
			'leave' => array(self::BELONGS_TO, 'EmployeeLeave', 'leave_id'),
			'hod' => array(self::BELONGS_TO, 'Employee', 'hod_id'),
			'staff2' => array(self::BELONGS_TO, 'Employee', 'while_away_staff_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'leave_id' => null,
			'staff_id' => null,
			'start_date' => Yii::t('app', 'Start Date'),
			'hod_id' => Yii::t('app', 'HoD/Supervisor'),
			'end_date' => Yii::t('app', 'End Date'),
			'total_days' => Yii::t('app', 'Total Days'),
			'taken_days' => Yii::t('app', 'Taken Days'),
			'rem_days' => Yii::t('app', 'Rem Days'),
			'status' => Yii::t('app', 'Status'),
			'is_latest' => Yii::t('app', 'Is Latest'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'staff' => null,
			'leave' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('leave_id', $this->leave_id);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('total_days', $this->total_days);
		$criteria->compare('taken_days', $this->taken_days);
		$criteria->compare('rem_days', $this->rem_days);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_latest', $this->is_latest);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}