<?php

/**
 * This is the model base class for the table "{{employee_document_action}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeDocumentAction".
 *
 * Columns in table "{{employee_document_action}}" available as properties of the model,
 * followed by relations of table "{{employee_document_action}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $document_id
 * @property integer $action_id
 * @property integer $user_id
 * @property integer $yr
 * @property integer $mt
 * @property integer $dy
 * @property integer $hr
 * @property integer $mn
 * @property integer $se
 * @property string $date_modified
 *
 * @property EmployeeDocument $document
 * @property User $user
 */
abstract class BaseEmployeeDocumentAction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_document_action}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeDocumentAction|EmployeeDocumentActions', $n);
	}

	public static function representingColumn() {
		return 'date_modified';
	}

	public function rules() {
		return array(
			array('document_id, action_id, user_id, yr, mt, dy, hr, mn, se', 'required'),
			array('document_id, action_id, user_id, yr, mt, dy, hr, mn, se', 'numerical', 'integerOnly'=>true),
			array('date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, document_id, action_id, user_id, yr, mt, dy, hr, mn, se, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'document' => array(self::BELONGS_TO, 'EmployeeDocument', 'document_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'document_id' => null,
			'action_id' => Yii::t('app', 'Action'),
			'user_id' => null,
			'yr' => Yii::t('app', 'Yr'),
			'mt' => Yii::t('app', 'Mt'),
			'dy' => Yii::t('app', 'Dy'),
			'hr' => Yii::t('app', 'Hr'),
			'mn' => Yii::t('app', 'Mn'),
			'se' => Yii::t('app', 'Se'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'document' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('document_id', $this->document_id);
		$criteria->compare('action_id', $this->action_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('yr', $this->yr);
		$criteria->compare('mt', $this->mt);
		$criteria->compare('dy', $this->dy);
		$criteria->compare('hr', $this->hr);
		$criteria->compare('mn', $this->mn);
		$criteria->compare('se', $this->se);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}