<?php

/**
 * This is the model base class for the table "{{employee_supervision}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeSupervision".
 *
 * Columns in table "{{employee_supervision}}" available as properties of the model,
 * followed by relations of table "{{employee_supervision}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $pf_number
 * @property string $student_name
 * @property string $period
 * @property boolean $status
 * @property string $date_modified
 *
 * @property Employee $pfNumber
 */
abstract class BaseEmployeeSupervision extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_supervision}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeSupervision|EmployeeSupervisions', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, pf_number, student_name, period', 'required'),
			array('title', 'length', 'max'=>500),
			array('pf_number, period, date_modified', 'length', 'max'=>30),
			array('student_name', 'length', 'max'=>50),
			array('status', 'safe'),
			array('status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, pf_number, student_name, period, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'pf_number' => null,
			'student_name' => Yii::t('app', 'Student Name'),
			'period' => Yii::t('app', 'Period'),
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'pfNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('student_name', $this->student_name, true);
		$criteria->compare('period', $this->period, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}