<?php

/**
 * This is the model base class for the table "{{position_name}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PositionName".
 *
 * Columns in table "{{position_name}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $grade_id
 * @property integer $category_id
 *
 */
abstract class BasePositionName extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{position_name}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PositionName|PositionNames', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('grade_id, category_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>300),
			array('grade_id, category_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, grade_id, category_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'grade_id' => Yii::t('app', 'Grade'),
			'category_id' => Yii::t('app', 'Category'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('grade_id', $this->grade_id);
		$criteria->compare('category_id', $this->category_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}