<?php

/**
 * This is the model base class for the table "{{emp_terms}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmploymentTerms".
 *
 * Columns in table "{{emp_terms}}" available as properties of the model,
 * followed by relations of table "{{emp_terms}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $date_modified
 *
 * @property Employee[] $employees
 * @property Staff[] $staffs
 */
abstract class BaseEmploymentTerms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{emp_terms}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Employment Terms|Employment Terms', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>50),
			array('date_modified', 'length', 'max'=>30),
			array('name, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employees' => array(self::HAS_MANY, 'Employee', 'emp_terms_id'),
			'staffs' => array(self::HAS_MANY, 'Staff', 'emp_terms_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'employees' => null,
			'staffs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}