<?php

/**
 * This is the model base class for the table "{{employee_leave_duration}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeLeaveDuration".
 *
 * Columns in table "{{employee_leave_duration}}" available as properties of the model,
 * followed by relations of table "{{employee_leave_duration}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $days
 * @property integer $category
 * @property string $date_modified
 *
 * @property EmployeeLeave[] $employeeLeaves
 */
abstract class BaseEmployeeLeaveDuration extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_leave_duration}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Leave Duration|Leave Durations', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, days, category', 'required'),
			array('days, category', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('date_modified', 'length', 'max'=>50),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, days, category, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeeLeaves' => array(self::HAS_MANY, 'EmployeeLeave', 'duration_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'days' => Yii::t('app', 'Days'),
			'category' => Yii::t('app', 'Working Days'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'employeeLeaves' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('days', $this->days);
		$criteria->compare('category', $this->category);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}