<?php

/**
 * This is the model base class for the table "{{doc_type}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DocType".
 *
 * Columns in table "{{doc_type}}" available as properties of the model,
 * followed by relations of table "{{doc_type}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $date_modified
 *
 * @property EmployeeDoc[] $employeeDocs
 */
abstract class BaseDocType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{doc_type}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Document Type|Document Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeeDocs' => array(self::HAS_MANY, 'EmployeeDoc', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'employeeDocs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}