<?php

/**
 * This is the model base class for the table "{{employee_contact}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeContact".
 *
 * Columns in table "{{employee_contact}}" available as properties of the model,
 * followed by relations of table "{{employee_contact}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $pf_number
 * @property string $home
 * @property integer $nationality_id
 * @property integer $county_id
 * @property string $postal_address
 * @property string $postal_code
 * @property string $town
 * @property string $office_telephone
 * @property string $mobile
 * @property string $email
 * @property string $date_modified
 *
 * @property Employee $pfNumber
 * @property Nationality $nationality
 * @property County $county
 */
abstract class BaseEmployeeContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_contact}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeContact|EmployeeContacts', $n);
	}

	public static function representingColumn() {
		return 'home';
	}

	public function rules() {
		return array(
			array('pf_number, home, faculty_id, school_id, department_id, nationality_id, county_id, title_id, mobile, office_email, designation, email, interest_area', 'required'),
			array('nationality_id, county_id, title_id, updated', 'numerical', 'integerOnly'=>true),
			array('pf_number, date_modified, mobile2, mobile', 'length', 'max'=>30),
			array('home, interest_area', 'length', 'max'=>150),
			array('email, email2, office_email','email'),
			array('email, email2', 'unique','message'=>'We already have somebody with that email address!'),
			array('mobile, mobile2', 'unique','message'=>'We already have somebody with that mobile phone number!'),
			array('postal_address, town, office_telephone, consultation_hours', 'length', 'max'=>100),
			array('postal_code', 'length', 'max'=>10),
			array('email2, email', 'length', 'max'=>300),
			array('postal_address, postal_code, town, office_telephone, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, pf_number, home, nationality_id, county_id, postal_address, postal_code, town, office_telephone, mobile, email, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
			'nationality' => array(self::BELONGS_TO, 'Nationality', 'nationality_id'),
			'county' => array(self::BELONGS_TO, 'County', 'county_id'),
			'faculty' => array(self::BELONGS_TO, 'Faculty', 'faculty_id'),
			'school' => array(self::BELONGS_TO, 'School', 'school_id'),
			'department' => array(self::BELONGS_TO, 'Department', 'department_id'),
			'title' => array(self::BELONGS_TO, 'EmployeeAcademicTitle', 'title_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pf_number' => null,
			'home' => Yii::t('app', 'Home'),
			'nationality_id' => null,
			'county_id' => null,
			'county_id' => Yii::t('app', 'County'),
			'country_id' => Yii::t('app', 'Country'),
			'faculty_id' => Yii::t('app', 'Faculty'),
			'school_id' => Yii::t('app', 'School'),
			'department_id' => Yii::t('app', 'Department'),
			'designation' => Yii::t('app', 'Current Designation'),
			'title_id' => Yii::t('app', 'Designation'),
			'postal_address' => Yii::t('app', 'Postal Address'),
			'postal_code' => Yii::t('app', 'Postal Code'),
			'town' => Yii::t('app', 'Town'),
			'office_telephone' => Yii::t('app', 'Office Telephone'),
			'mobile' => Yii::t('app', 'Primary Mobile No'),
			'email' => Yii::t('app', 'Primary Personal Email'),
			'mobile2' => Yii::t('app', 'Alternative Mobile No'),
			'email2' => Yii::t('app', 'Alternative Personal Email'),
			'interest_area' => Yii::t('app', 'Profession/Interest Area'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'pfNumber' => null,
			'nationality' => null,
			'county' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('home', $this->home, true);
		$criteria->compare('nationality_id', $this->nationality_id);
		$criteria->compare('county_id', $this->county_id);
		$criteria->compare('postal_address', $this->postal_address, true);
		$criteria->compare('postal_code', $this->postal_code, true);
		$criteria->compare('town', $this->town, true);
		$criteria->compare('office_telephone', $this->office_telephone, true);
		$criteria->compare('mobile', $this->mobile, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}