<?php

/**
 * This is the model base class for the table "{{employee_nok_level}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeNokLevel".
 *
 * Columns in table "{{employee_nok_level}}" available as properties of the model,
 * followed by relations of table "{{employee_nok_level}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $level
 * @property string $date_modified
 *
 * @property EmployeeNok[] $employeeNoks
 */
abstract class BaseEmployeeNokLevel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_nok_level}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Next of Kin Level|Next of Kin Levels', $n);
	}

	public static function representingColumn() {
		return 'level';
	}

	public function rules() {
		return array(
			array('level', 'required'),
			array('level, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, level, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'employeeNoks' => array(self::HAS_MANY, 'EmployeeNok', 'level_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'level' => Yii::t('app', 'Level'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'employeeNoks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('level', $this->level, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}