<?php

/**
 * This is the model base class for the table "{{employee_publication}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeePublication".
 *
 * Columns in table "{{employee_publication}}" available as properties of the model,
 * followed by relations of table "{{employee_publication}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $link
 * @property string $pf_number
 * @property boolean $status
 * @property string $date_modified
 *
 * @property Employee $pfNumber
 */
abstract class BaseEmployeePublication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_publication}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeePublication|EmployeePublications', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, link, pf_number', 'required'),
			array('link', 'url', 'defaultScheme' => 'http'),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('status', 'safe'),
			array('status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, link, pf_number, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'link' => Yii::t('app', 'Link'),
			'pf_number' => null,
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'pfNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}