<?php

/**
 * This is the model base class for the table "{{employee_leave_special_holiday}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeLeaveSpecialHoliday".
 *
 * Columns in table "{{employee_leave_special_holiday}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $year
 * @property string $date
 * @property string $date_modified
 *
 */
abstract class BaseEmployeeLeaveSpecialHoliday extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_leave_special_holiday}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Leave Special Holiday|Leave Special Holidays', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('year, date', 'required'),
			array('year', 'numerical', 'integerOnly'=>true),
			array('date, date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, year, date, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'year' => Yii::t('app', 'Year'),
			'date' => Yii::t('app', 'Date'),
			'date_modified' => Yii::t('app', 'Date Modified'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('year', $this->year);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}