<?php

/**
 * This is the model base class for the table "{{employee_work}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeWork".
 *
 * Columns in table "{{employee_work}}" available as properties of the model,
 * followed by relations of table "{{employee_work}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $position
 * @property string $pf_number
 * @property string $institution
 * @property string $starting_date
 * @property string $ending_date
 * @property boolean $status
 * @property string $date_modified
 *
 * @property Employee $pfNumber
 */
abstract class BaseEmployeeWork extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_work}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeWork|EmployeeWorks', $n);
	}

	public static function representingColumn() {
		return 'position';
	}

	public function rules() {
		return array(
			array('position, pf_number,institution, country_id, starting_date, ending_date', 'required'),
			array('position, starting_date, ending_date', 'length', 'max'=>100),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('institution', 'length', 'max'=>200),
			array('status', 'safe'),
			array('institution, status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, position, pf_number, institution, starting_date, ending_date, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
			'country' => array(self::BELONGS_TO, 'EmployeeCountry', 'country_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'position' => Yii::t('app', 'Position'),
			'pf_number' => null,
			'institution' => Yii::t('app', 'Institution'),
			'country_id' => Yii::t('app', 'Country'),
			'starting_date' => Yii::t('app', 'Starting Date'),
			'ending_date' => Yii::t('app', 'Ending Date'),
			'status' => Yii::t('app', 'Is Active?'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'pfNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('position', $this->position, true);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('institution', $this->institution, true);
		$criteria->compare('starting_date', $this->starting_date, true);
		$criteria->compare('ending_date', $this->ending_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}