<?php

/**
 * This is the model base class for the table "{{office}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Office".
 *
 * Columns in table "{{office}}" available as properties of the model,
 * followed by relations of table "{{office}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $date_modified
 * @property integer $top_level
 * @property integer $level
 *
 * @property Staff[] $staffs
 * @property Office $topLevel
 * @property Office[] $offices
 * @property EmployeeEmployment[] $employeeEmployments
 * @property Position[] $positions
 */
abstract class BaseOffice extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{office}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Office|Offices', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('top_level, level', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('date_modified', 'length', 'max'=>30),
			array('date_modified, top_level, level', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, date_modified, top_level, level', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staffs' => array(self::HAS_MANY, 'Staff', 'office_id'),
			'topLevel' => array(self::BELONGS_TO, 'Office', 'top_level'),
			'offices' => array(self::HAS_MANY, 'Office', 'top_level'),
			'employeeEmployments' => array(self::HAS_MANY, 'EmployeeEmployment', 'office_id'),
			'positions' => array(self::HAS_MANY, 'Position', 'office_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'top_level' => null,
			'level' => Yii::t('app', 'Level'),
			'staffs' => null,
			'topLevel' => 'Top Office',
			'offices' => null,
			'employeeEmployments' => null,
			'positions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('LOWER(name)', strtolower($this->name), true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('top_level', $this->top_level);
		$criteria->compare('level', $this->level);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}