<?php

/**
 * This is the model base class for the table "{{employee_course}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmployeeCourse".
 *
 * Columns in table "{{employee_course}}" available as properties of the model,
 * followed by relations of table "{{employee_course}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $pf_number
 * @property string $course_name
 * @property string $brief_description
 * @property string $elearning_link
 * @property string $institution
 * @property integer $country_id
 * @property string $starting_date
 * @property string $ending_date
 * @property boolean $currently_on
 * @property string $date_modified
 *
 * @property Country $country
 * @property Employee $pfNumber
 */
abstract class BaseEmployeeCourse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{employee_course}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmployeeCourse|EmployeeCourses', $n);
	}

	public static function representingColumn() {
		return 'course_name';
	}

	public function rules() {
		return array(
			array('pf_number, course_name, brief_description, institution, country_id, starting_date, ending_date', 'required'),
			array('elearning_link', 'url', 'defaultScheme' => 'http'),
			array('country_id', 'numerical', 'integerOnly'=>true),
			array('pf_number, date_modified', 'length', 'max'=>30),
			array('course_name, elearning_link', 'length', 'max'=>300),
			array('brief_description', 'length', 'max'=>500),
			array('institution', 'length', 'max'=>200),
			array('starting_date, ending_date', 'length', 'max'=>100),
			array('currently_on', 'safe'),
			array('elearning_link, currently_on, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, pf_number, course_name, brief_description, elearning_link, institution, country_id, starting_date, ending_date, currently_on, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'pfNumber' => array(self::BELONGS_TO, 'Employee', 'pf_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pf_number' => null,
			'course_name' => Yii::t('app', 'Course Name'),
			'brief_description' => Yii::t('app', 'Brief Description'),
			'elearning_link' => Yii::t('app', 'Elearning Link'),
			'institution' => Yii::t('app', 'Institution'),
			'country_id' => null,
			'starting_date' => Yii::t('app', 'Starting Date'),
			'ending_date' => Yii::t('app', 'Ending Date'),
			'currently_on' => Yii::t('app', 'Currently On'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'country' => null,
			'pfNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pf_number', $this->pf_number);
		$criteria->compare('course_name', $this->course_name, true);
		$criteria->compare('brief_description', $this->brief_description, true);
		$criteria->compare('elearning_link', $this->elearning_link, true);
		$criteria->compare('institution', $this->institution, true);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('starting_date', $this->starting_date, true);
		$criteria->compare('ending_date', $this->ending_date, true);
		$criteria->compare('currently_on', $this->currently_on);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}