<?php

/**
 * This is the model base class for the table "{{kcse_qualification}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "KcseQualification".
 *
 * Columns in table "{{kcse_qualification}}" available as properties of the model,
 * followed by relations of table "{{kcse_qualification}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $app_id
 * @property string $name
 * @property integer $category_id
 * @property integer $year
 * @property string $grade
 * @property string $school
 * @property string $date_modified
 *
 * @property AcQualCategory $category
 * @property Applicant $app
 */
abstract class BaseKcseQualification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{kcse_qualification}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'KcseQualification|KcseQualifications', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('app_id, name, category_id, year, grade, school, date_modified', 'required'),
			array('app_id, category_id, year', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('grade', 'length', 'max'=>200),
			array('school', 'length', 'max'=>300),
			array('date_modified', 'length', 'max'=>30),
			array('id, app_id, name, category_id, year, grade, school, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'AcQualCategory', 'category_id'),
			'app' => array(self::BELONGS_TO, 'Applicant', 'app_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'app_id' => null,
			'name' => Yii::t('app', 'Name'),
			'category_id' => null,
			'year' => Yii::t('app', 'Year'),
			'grade' => Yii::t('app', 'Grade'),
			'school' => Yii::t('app', 'School'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'category' => null,
			'app' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('app_id', $this->app_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('year', $this->year);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('school', $this->school, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}