<?php

/**
 * This is the model base class for the table "{{app_course}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ApplicantCourse".
 *
 * Columns in table "{{app_course}}" available as properties of the model,
 * followed by relations of table "{{app_course}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $app_id
 * @property string $programme_id
 * @property string $date_modified
 *
 * @property Applicant $app
 * @property Programme $programme
 */
abstract class BaseApplicantCourse extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{app_course}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ApplicantCourse|ApplicantCourses', $n);
	}

	public static function representingColumn() {
		return 'date_modified';
	}

	public function rules() {
		return array(
			array('app_id, programme_id, date_modified', 'required'),
			array('app_id', 'numerical', 'integerOnly'=>true),
			array('programme_id, date_modified', 'length', 'max'=>30),
			array('id, app_id, programme_id, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'app' => array(self::BELONGS_TO, 'Applicant', 'app_id'),
			'programme' => array(self::BELONGS_TO, 'Programme', 'programme_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'app_id' => null,
			'programme_id' => null,
			'date_modified' => Yii::t('app', 'Date Modified'),
			'app' => null,
			'programme' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('app_id', $this->app_id);
		$criteria->compare('programme_id', $this->programme_id);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}