<?php

/**
 * This is the model base class for the table "{{email_notification}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmailNotification".
 *
 * Columns in table "{{email_notification}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $notification_name
 * @property integer $user_id
 * @property integer $category
 * @property string $time_to_trigger
 * @property string $date_time_gerated
 * @property integer $status
 * @property string $date_time_sent
 *
 */
abstract class BaseEmailNotification extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{email_notification}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmailNotification|EmailNotifications', $n);
	}

	public static function representingColumn() {
		return 'notification_name';
	}

	public function rules() {
		return array(
			array('notification_name, user_id, category, time_to_trigger, date_time_gerated, email, subject, message, status', 'required'),
			array('user_id, category, status', 'numerical', 'integerOnly'=>true),
			array('notification_name', 'length', 'max'=>50),
			array('email', 'length', 'max'=>3000),
			array('time_to_trigger, date_time_gerated, date_time_sent', 'length', 'max'=>30),
			array('date_time_sent', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, notification_name, user_id, category, time_to_trigger, date_time_gerated, status, date_time_sent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'notification_name' => Yii::t('app', 'Notification Name'),
			'user_id' => Yii::t('app', 'User'),
			'category' => Yii::t('app', 'Category'),
			'time_to_trigger' => Yii::t('app', 'Time To Trigger'),
			'date_time_gerated' => Yii::t('app', 'Date Time Gerated'),
			'status' => Yii::t('app', 'Status'),
			'date_time_sent' => Yii::t('app', 'Date Time Sent'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('notification_name', $this->notification_name, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('category', $this->category);
		$criteria->compare('time_to_trigger', $this->time_to_trigger, true);
		$criteria->compare('date_time_gerated', $this->date_time_gerated, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_time_sent', $this->date_time_sent, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}