<?php

/**
 * This is the model base class for the table "{{exam_type}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExamType".
 *
 * Columns in table "{{exam_type}}" available as properties of the model,
 * followed by relations of table "{{exam_type}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $status
 * @property string $date_modified
 *
 * @property Score[] $scores
 */
abstract class BaseExamType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{exam_type}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Type of Exam | Types of Exam', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('description', 'length', 'max'=>300),
			array('date_modified', 'length', 'max'=>30),
			array('name, description, status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'scores' => array(self::HAS_MANY, 'Score', 'exam_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'scores' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}