<?php

/**
 * This is the model base class for the table "{{score}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Score".
 *
 * Columns in table "{{score}}" available as properties of the model,
 * followed by relations of table "{{score}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $semester_id
 * @property string $student_reg
 * @property integer $course_unit_id
 * @property integer $exam_type_id
 * @property integer $year_of_study
 * @property integer $semester_of_study
 * @property integer $marks_obtained
 * @property integer $marks_total
 * @property string $grade
 * @property integer $status
 * @property string $remarks
 * @property string $date_modified
 *
 * @property Semester $semester
 * @property Student $studentReg
 * @property CourseUnit $courseUnit
 * @property ExamType $examType
 */
abstract class BaseScore extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{score}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Score|Scores', $n);
	}

	public static function representingColumn() {
		return 'student_reg';
	}

	public function rules() {
		return array(
			array('semester_id, student_reg, course_unit_id, exam_type_id, year_of_study, semester_of_study, marks_obtained, marks_total', 'required'),
			array('marks_obtained, marks_total', 'numerical'),
			array('semester_id, course_unit_id, exam_type_id, year_of_study, semester_of_study, status', 'numerical', 'integerOnly'=>true),
			array('student_reg, date_modified', 'length', 'max'=>30),
			array('grade', 'length', 'max'=>3),
			array('remarks', 'length', 'max'=>100),
			array('grade, status, remarks, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, semester_id, student_reg, course_unit_id, exam_type_id, year_of_study, semester_of_study, marks_obtained, marks_total, grade, status, remarks, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'semester' => array(self::BELONGS_TO, 'Semester', 'semester_id'),
			'studentReg' => array(self::BELONGS_TO, 'Student', 'student_reg'),
			'courseUnit' => array(self::BELONGS_TO, 'CourseUnit', 'course_unit'),
			'examType' => array(self::BELONGS_TO, 'ExamType', 'exam_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'semester_id' => null,
			'student_reg' => null,
			'course_unit_id' => null,
			'exam_type_id' => null,
			'year_of_study' => Yii::t('app', 'Year Of Study'),
			'semester_of_study' => Yii::t('app', 'Semester Of Study'),
			'marks_obtained' => Yii::t('app', 'Marks'),
			'marks_total' => Yii::t('app', 'Marks Total'),
			'grade' => Yii::t('app', 'Grade'),
			'status' => Yii::t('app', 'Status'),
			'remarks' => Yii::t('app', 'Remarks'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'hours' => Yii::t('app', 'Contact Hours'),
			'semester' => null,
			'studentReg' => null,
			'courseUnit' => null,
			'examType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('semester_id', $this->semester_id);
		$criteria->compare('student_reg', $this->student_reg);
		// <><><> 
		$criteria->compare('course_unit', $this->course_unit);
		$criteria->compare('exam_type_id', $this->exam_type_id);
		$criteria->compare('year_of_study', $this->year_of_study);
		$criteria->compare('semester_of_study', $this->semester_of_study);
		$criteria->compare('marks_obtained', $this->marks_obtained);
		$criteria->compare('marks_total', $this->marks_total);
		$criteria->compare('grade', $this->grade, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}