<?php

/**
 * This is the model base class for the table "{{course_registration}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CourseRegistration".
 *
 * Columns in table "{{course_registration}}" available as properties of the model,
 * followed by relations of table "{{course_registration}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $semester_id
 * @property string $student_reg
 * @property string $course_unit_id
 * @property integer $status
 * @property string $date_modified
 *
 * @property CourseUnit $courseUnit
 * @property Semester $semester
 * @property Student $studentReg
 */
abstract class BaseCourseRegistration extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{course_registration}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Course Registration|Course Registrations', $n);
	}

	public static function representingColumn() {
		return 'student_reg';
	}

	public function rules() {
		return array(
			array('semester_id, student_reg, course_unit_id', 'required'),
			array('semester_id, status', 'numerical', 'integerOnly'=>true),
			array('student_reg, date_modified', 'length', 'max'=>30),
			array('course_unit_id', 'length', 'max'=>20),
			array('status, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, semester_id, student_reg, course_unit_id, status, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'courseUnit' => array(self::BELONGS_TO, 'CourseUnit', 'course_unit_id'),
			'semester' => array(self::BELONGS_TO, 'Semester', 'semester_id'),
			'studentReg' => array(self::BELONGS_TO, 'Student', 'student_reg'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'semester_id' => null,
			'student_reg' => null,
			'course_unit_id' => null,
			'status' => Yii::t('app', 'Status'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'courseUnit' => null,
			'semester' => null,
			'studentReg' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('semester_id', $this->semester_id);
		$criteria->compare('student_reg', $this->student_reg);
		$criteria->compare('course_unit_id', $this->course_unit_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}