<?php

/**
 * This is the model base class for the table "{{score_processing}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ScoreProcessing".
 *
 * Columns in table "{{score_processing}}" available as properties of the model,
 * followed by relations of table "{{score_processing}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $class_code
 * @property integer $year_of_study
 * @property string $total
 * @property string $date_modified
 * @property integer $category
 * @property integer $author
 *
 * @property User $author0
 */
abstract class BaseScoreProcessing extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{score_processing}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ScoreProcessing|ScoreProcessings', $n);
	}

	public static function representingColumn() {
		return 'class_code';
	}

	public function rules() {
		return array(
			array('year_of_study, category, author', 'numerical', 'integerOnly'=>true),
			array('class_code, total', 'length', 'max'=>20),
			array('date_modified', 'length', 'max'=>30),
			array('class_code, year_of_study, total, date_modified, category, author', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, class_code, year_of_study, total, date_modified, category, author', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'author0' => array(self::BELONGS_TO, 'User', 'author'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'class_code' => Yii::t('app', 'Class Code'),
			'year_of_study' => Yii::t('app', 'Year Of Study'),
			'total' => Yii::t('app', 'Total Number of Students'),
			'date_modified' => Yii::t('app', 'Date'),
			'category' => Yii::t('app', 'Category'),
			'author' => null,
			'author0' => 'User',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('class_code', $this->class_code, true);
		$criteria->compare('year_of_study', $this->year_of_study);
		$criteria->compare('total', $this->total, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('category', $this->category);
		$criteria->compare('author', $this->author);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}