<?php

/**
 * This is the model base class for the table "{{ict_service_request_action}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IctServiceRequestAction".
 *
 * Columns in table "{{ict_service_request_action}}" available as properties of the model,
 * followed by relations of table "{{ict_service_request_action}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $service_id
 * @property string $description
 * @property string $date_modified
 *
 * @property IctServiceRequest $service
 * @property User $user
 */
abstract class BaseIctServiceRequestAction extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{ict_service_request_action}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IctServiceRequestAction|IctServiceRequestActions', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('user_id, service_id, description', 'required'),
			array('user_id, service_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>600),
			array('date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, service_id, description, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'service' => array(self::BELONGS_TO, 'IctServiceRequest', 'service_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'service_id' => null,
			'description' => Yii::t('app', 'Description'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'service' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('service_id', $this->service_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}