<?php

/**
 * This is the model base class for the table "{{ict_service_request}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IctServiceRequest".
 *
 * Columns in table "{{ict_service_request}}" available as properties of the model,
 * followed by relations of table "{{ict_service_request}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $type_id
 * @property integer $office_id
 * @property string $description
 * @property string $date_modified
 * @property integer $status
 *
 * @property Office $office
 * @property IctEquipment $type
 * @property User $user
 * @property IctServiceRequestAction[] $ictServiceRequestActions
 */
abstract class BaseIctServiceRequest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{ict_service_request}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IctServiceRequest|IctServiceRequests', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('user_id, type_id, office_id, description, status', 'required'),
			array('user_id, type_id, office_id, status', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>600),
			array('date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, type_id, office_id, description, date_modified, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'office' => array(self::BELONGS_TO, 'Office', 'office_id'),
			'type' => array(self::BELONGS_TO, 'IctEquipmentType', 'type_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'ictServiceRequestActions' => array(self::HAS_MANY, 'IctServiceRequestAction', 'service_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => 'Staff',
			'type_id' => null,
			'office_id' => null,
			'description' => Yii::t('app', 'Description'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'status' => Yii::t('app', 'Status'),
			'statustxt' => Yii::t('app', 'Status'),
			'office' => null,
			'type' => null,
			'user' => 'Staff',
			'ictServiceRequestActions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		//$criteria->compare('user_id', $this->user_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('office_id', $this->office_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('status', $this->status);
		$criteria->order='id DESC';
		$criteria->order='status ASC';
		$criteria->condition = "user_id = '".Yii::app()->user->id."' ";
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'pagination'=>array('pageSize'=>100),
		));
	}
}