<?php

/**
 * This is the model base class for the table "{{ict_equipment_access}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IctEquipmentAccess".
 *
 * Columns in table "{{ict_equipment_access}}" available as properties of the model,
 * followed by relations of table "{{ict_equipment_access}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $type_id
 * @property string $date_accessed
 * @property string $time_in
 * @property string $time_out
 * @property string $reason
 * @property string $date_modified
 *
 * @property IctEquipment $type
 * @property User $user
 */
abstract class BaseIctEquipmentAccess extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{ict_equipment_access}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ICT Equipment Access|ICT Equipment Accesses', $n);
	}

	public static function representingColumn() {
		return 'date_accessed';
	}

	public function rules() {
		return array(
			array('user_id, type_id, date_accessed, time_in, time_out, reason', 'required'),
			array('user_id, type_id', 'numerical', 'integerOnly'=>true),
			array('date_accessed, time_in, time_out, date_modified', 'length', 'max'=>30),
			array('reason', 'length', 'max'=>300),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, type_id, date_accessed, time_in, time_out, reason, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'type' => array(self::BELONGS_TO, 'IctEquipment', 'type_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'type_id' => null,
			'date_accessed' => Yii::t('app', 'Date Accessed'),
			'time_in' => Yii::t('app', 'Time In'),
			'time_out' => Yii::t('app', 'Time Out'),
			'reason' => Yii::t('app', 'Reason'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'type' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('date_accessed', $this->date_accessed, true);
		$criteria->compare('time_in', $this->time_in, true);
		$criteria->compare('time_out', $this->time_out, true);
		$criteria->compare('reason', $this->reason, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}