<?php

/**
 * This is the model base class for the table "{{ict_equipment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IctEquipment".
 *
 * Columns in table "{{ict_equipment}}" available as properties of the model,
 * followed by relations of table "{{ict_equipment}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $type_id
 * @property string $common_name
 * @property string $description
 * @property string $mac_address
 * @property string $date_modified
 *
 * @property IctEquipmentAccess[] $ictEquipmentAccesses
 * @property IctEquipmentType $type
 * @property IctServiceRequest[] $ictServiceRequests
 */
abstract class BaseIctEquipment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{ict_equipment}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ICT Equipment/ Server|ICT Equipment / Servers', $n);
	}

	public static function representingColumn() {
		return 'common_name';
	}

	public function rules() {
		return array(
			array('type_id, common_name, description, mac_address', 'required'),
			array('type_id', 'numerical', 'integerOnly'=>true),
			array('common_name', 'length', 'max'=>100),
			array('description', 'length', 'max'=>300),
			array('mac_address', 'length', 'max'=>50),
			array('date_modified', 'length', 'max'=>30),
			array('date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type_id, common_name, description, mac_address, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ictEquipmentAccesses' => array(self::HAS_MANY, 'IctEquipmentAccess', 'type_id'),
			'type' => array(self::BELONGS_TO, 'IctEquipmentType', 'type_id'),
			'ictServiceRequests' => array(self::HAS_MANY, 'IctServiceRequest', 'type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type_id' => null,
			'common_name' => Yii::t('app', 'Common Name'),
			'description' => Yii::t('app', 'Description'),
			'mac_address' => Yii::t('app', 'Mac Address'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'ictEquipmentAccesses' => null,
			'type' => null,
			'ictServiceRequests' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('common_name', $this->common_name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('mac_address', $this->mac_address, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}